### ISSUE TITLE
No module named 'PassivePySrc.PassivePyRules_FullPassive'

### ISSUE THREAD

**Issue by aidarahim** [mitramir55/PassivePy#1]
I followed the instructions in the Readme.
Instruction set 1: Runs fine
Instruction set 2: ModuleNotFoundError: No module named 'PassivePySrc.PassivePyRules_FullPassive'

I tried on Databricks and on my local machine but received the same error.

Your help is much appreciated - thanks.

**Comment by mitramir55** [comment]
Hi @aidarahim, thanks for reporting the issue.
Our package is in the testing stage. It's been modified in the past week and the readme file was a bit outdated. I updated it, but I suggest you take a look at [this colab notebook](https://colab.research.google.com/drive/1xMAwUo96SBtPmbg6-3fd4hPI0lQ0roUo?usp=sharing) that I put together, ran, and made sure it works without any errors. Please tell us if there was anything else we could do.

**Comment by aidarahim** [comment]
This solved my issue. Thank you very much!
